name: Playwright Tests
on: #event triggers for the workflow when code is pushed to the repository or when a pull request is opened against the main or master branch test
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs: #a set of steps that will be executed as part of the workflow, in this case we have a single job called "test" that will run our Playwright tests
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      #dont need to isntall the browsers in the github workflow because we will be running the tests in the cloud environment, so we will use the browsers that are already installed in the cloud environment
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
      #for azure login if we want to include the azure login step in the workflow, we will need to add the azure/login action and use the credentials stored in the repository secrets to authenticate with Azure. This will allow us to run our Playwright tests in the Azure cloud environment.
    - name: Azure Login
      uses: azure/login@v3
      with:
        #tests will all be triggered in the cloud environment, so we will use the credentials stored in the repository secrets to authenticate with Azure
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Generate Linux snapshots
      env:
        PLAYWRIGHT_SERVICE_URL: ${{ vars.PLAYWRIGHT_SERVICE_URL }}
      run: npx playwright test --config=playwright.service.config.js --update-snapshots
    - name: Run Playwright tests
      env:
        #tests will all be triggered in the cloud environment, so we will use the service URL stored in the repository variables to connect to the Playwright service in Azure
        PLAYWRIGHT_SERVICE_URL: ${{ vars.PLAYWRIGHT_SERVICE_URL }}
      run: npx playwright test --config=playwright.service.config.js --workers=4
        # local command to run tests npx playwright test
        # cloud command to run tests npx playwright test --config=playwright.service.config.ts --workers=4
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
